version: "3"
services:
    www:
        build: ./dockers/apache/
        ports: 
            - "8001:80"
        volumes:
#            - ./src:/var/www/html/
            - ./conf/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./src:/var/www/html/
        links:
            - db
        networks:
            - default
    scrap:
        image: python
        working_dir: /root/
        volumes:
            - ./src2:/root
        links:
            - db
        networks:
            - default
        tty: true
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: analizerdb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            #- ./dump:/docker-entrypoint-initdb.d
            - ./conf/mysql/:/etc/mysql/conf.d 
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
